-- Make "the most recent consent event" unambiguous.
--
-- has_active_biometric_consent() picked the latest row by occurred_at, whose
-- default was now() — the transaction start time, identical for every row
-- written in one transaction. A grant and a withdrawal recorded together (or
-- inside the same clock tick) therefore had no defined order, and the function
-- could report consent as active after it had been withdrawn. An RLS behaviour
-- test caught this before any data existed.
--
-- A bigserial gives strict insertion order independent of the clock. It is the
-- ordering key; occurred_at stays as the human-meaningful timestamp.

alter table consent_events add column seq bigint generated by default as identity;

-- clock_timestamp() is the real wall clock at statement time rather than at
-- transaction start, so the recorded time matches when the event actually
-- happened even inside a multi-statement transaction.
alter table consent_events alter column occurred_at set default clock_timestamp();

create unique index consent_events_user_seq_idx on consent_events (user_id, seq desc);

create or replace function has_active_biometric_consent(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select action = 'granted'
      from consent_events
      where user_id = target_user
      order by seq desc
      limit 1
    ),
    false
  );
$$;
